# Change these first
owner: serenov7 # Your GitHub organization or username, where this repository lives
repo: status.sereno.one # The name of this repository

sites:
  - name: Drive
    url: https://drive.sereno.one
  - name: GitLab
    url: https://git.sereno.one
  - name: OpenWebUI
    url: https://ai.sereno.one
  - name: Portfolio
    url: https://sereno.one
  - name: CDN
    url: https://cdn.sereno.one

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sereno.one
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.sereno.one/i/morch.png
  name: Sereno Status
  introTitle: "Live status of all the different Sereno Services"
  introMessage: March 7th best girl
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
